# Generated by Django 4.2.7 on 2023-11-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RepresentanteEntrenador',
            fields=[
                ('coach_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('team_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('partido_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('goles_local', models.IntegerField(default=0)),
                ('goles_visita', models.IntegerField(default=0)),
                ('id_local', models.ForeignKey(db_column='id_local', on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='liga_afm_app.equipos')),
                ('id_visita', models.ForeignKey(db_column='id_visita', on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visita', to='liga_afm_app.equipos')),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=100)),
                ('player_lastName', models.CharField(max_length=100)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga_afm_app.equipos')),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partido_id', models.IntegerField()),
                ('jugador_id', models.IntegerField()),
                ('amarillas', models.IntegerField(default=0)),
                ('rojas', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('partido_id', 'jugador_id')},
            },
        ),
    ]
