# Generated by Django 4.2.7 on 2023-11-17 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liga_afm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coach',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('score1', models.IntegerField(default=0, null=True)),
                ('score2', models.IntegerField(default=0, null=True)),
                ('winner', models.IntegerField(default=None, null=True)),
                ('hour', models.TimeField()),
                ('matchweek', models.IntegerField()),
                ('played', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('yellowcards', models.IntegerField(default=0)),
                ('redcards', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='playermatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('yellowcards', models.IntegerField()),
                ('redcards', models.IntegerField()),
                ('owngoals', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga_afm_app.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga_afm_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchplayed', models.IntegerField()),
                ('matchwon', models.IntegerField()),
                ('matchdraw', models.IntegerField()),
                ('matchlost', models.IntegerField()),
                ('goalsfor', models.IntegerField()),
                ('goalsagainst', models.IntegerField()),
                ('goalsdifference', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='webAdmin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='EstadisticasPartido',
        ),
        migrations.RemoveField(
            model_name='jugadores',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='id_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='id_visita',
        ),
        migrations.DeleteModel(
            name='RepresentanteEntrenador',
        ),
        migrations.DeleteModel(
            name='Equipos',
        ),
        migrations.DeleteModel(
            name='Jugadores',
        ),
        migrations.DeleteModel(
            name='Partido',
        ),
        migrations.AddField(
            model_name='tables',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga_afm_app.team', unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga_afm_app.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='liga_afm_app.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='liga_afm_app.team'),
        ),
        migrations.AddField(
            model_name='coach',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga_afm_app.team'),
        ),
    ]
