# Generated by Django 4.2.7 on 2023-11-21 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liga_afm_app', '0002_coach_match_player_playermatch_tables_team_webadmin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='matchweek',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='goalsdifference',
        ),
    ]
